<p class="session-note">// ${textOr(_res.footerText!'', _res.defaultFooterText!'Keep the process. Share what you learn.')?html}<#if (webs.icp!'')?has_content><br>${webs.icp?html}</#if></p>
<div class="terminal-output" data-terminal-output aria-live="polite" hidden></div>
</main>
<div class="terminal-input-area"><form data-terminal-form action="${searchUrl?html}" method="post" class="terminal-form"><label for="terminal-input"><span>${terminalUser?html}@${terminalHost?html}</span><b>:~$</b></label><input id="terminal-input" data-terminal-input name="key" type="search" autocomplete="off" spellcheck="false" required aria-label="${(_res.search!'Search')?html}" data-command-label="${(_res.terminalInput!'Blog command')?html}" data-command-placeholder="${(_res.terminalPlaceholder!'help')?html}" placeholder="${(_res.searchPlaceholder!'Search…')?html}"><button type="submit" aria-label="${(_res.submitSearch!'Submit')?html}">↵</button></form><p class="terminal-tip"><#if log??>${_res.terminalRead!'↑/↓ scroll · Space page · q exit · : command'}<#else>${_res.sessionReadmeHint!'↑/↓ select · Enter read · / search · : command'}</#if></p><noscript><p class="terminal-search-tip">${_res.search!'Search'}: ${_res.searchPlaceholder!'Enter a search term'}</p></noscript></div>
<footer class="terminal-status"><span><a href="${baseUrl}">${terminalUser?html}</a> <span class="status-path">~/blog</span></span><span class="status-hint"><#if log??>LESS<#else>INDEX</#if></span><span>UTF-8<span class="status-powered"> · <a href="https://www.zrlog.com">ZrLog</a></span></span></footer>
</div>
<details class="navigation-source"><summary>${_res.terminalSections!'Directories'}</summary><nav aria-label="${(_res.categories!'Categories')?html}"><#list (init.types![]) as type><a data-terminal-kind="categories" href="${type.url?html}">${type.typeName?html}</a></#list></nav><nav aria-label="${(_res.tags!'Tags')?html}"><#list (init.tags![]) as tag><a data-terminal-kind="tags" href="${tag.url?html}">${tag.text?html}</a></#list></nav><nav aria-label="${(_res.archives!'Archives')?html}"><#list (init.archiveList![]) as item><a data-terminal-kind="archives" href="${item.url?html}">${item.text?html}</a></#list></nav><nav aria-label="${(_res.links!'Links')?html}"><#list (init.links![]) as link><a data-terminal-kind="links" href="${link.url?html}">${link.linkName?html}</a></#list></nav></details>
<dialog class="command-palette" id="command-palette" aria-labelledby="command-title"><div class="command-heading"><h2 id="command-title">${_res.search!'Search'}</h2><button type="button" data-command-close aria-label="${(_res.close!'Close')?html}">[esc]</button></div><form action="${searchUrl?html}" method="post" role="search"><label class="sr-only" for="command-input">${_res.search!'Search'}</label><span aria-hidden="true">/</span><input id="command-input" name="key" type="search" placeholder="${(_res.searchPlaceholder!'Search…')?html}" autocomplete="off" required><button type="submit" aria-label="${(_res.submitSearch!'Search')?html}">↵</button></form><p class="command-hint">${_res.commandHint!'Enter to search. Tab to navigate.'}</p><nav class="command-links" aria-label="${(_res.navigation!'Navigation')?html}"><a href="${baseUrl}" data-command-link>~/ ${_res.home!'Home'}</a><#list (init.logNavs![]) as item><a href="${item.url?html}" data-command-link>${item.navName?html}</a></#list><#list (init.types![]) as type><a href="${type.url?html}" data-command-link>./${type.typeName?html}</a></#list></nav></dialog>
<#include "terminal-data.ftl">
<#if (webs.webCm!'')?has_content>${webs.webCm}</#if>
</body></html>
